### ISSUE TITLE
Basic UI

### ISSUE THREAD

**Issue by sinksinksink** [sinksinksink/FlyingDrunks#2]
We need to investigate how to implement a UI. Suggest Shaun tries this out using the Blueprint system (may require some groundwork in how Blueprints work).

<b>Check out a few of these:</b> https://www.unrealengine.com/blog/blueprint-basics

<b>Specific to UI (starts at stage 2, basic setup is already done as well as altering health):</b> https://docs.unrealengine.com/latest/INT/Engine/UMG/QuickStart/2/index.html

Could also be of use: 
https://docs.unrealengine.com/latest/INT/Engine/UMG/index.html
https://wiki.unrealengine.com/Blueprint_Basic_Multiplayer_HUD

**Comment by sinksinksink** [comment]
Have added a folder with the blueprint for the in game UI and done necessary basic setup in the character blueprint to assign the UI. 

When left mouse is pressed health decreases by 10. Also added debug message for this. 

You'll need to figure out how to get the player variables into the UI (see the first tutorial above).

**Comment by shauncg** [comment]
Used this: https://www.youtube.com/watch?v=leFOIw1sFmE
For establishing how BPs communicate with each other. 

And this: https://www.youtube.com/watch?v=ZsBedOxInvk
For establishing how triggers & actors communicate via a BP. 

Going to use this: https://www.youtube.com/watch?v=jWVUr-i5zaM
To start looking into UI stuff.

**Comment by shauncg** [comment]
I've read through the HUD tutorial and it all seems pretty simple. 

Nb. I'm going to initially set up just an active health bar which utilises actual health values. Obviously down the line this will need inverting so rather than starting at 100 and dropping, it starts at 0 and climbs to represent heat build up. 

I will also put in place dummy (inactive) elements for the other anticipated UI elements, i.e. for other team members, poss. score / time remaining (although these latter two we talked about maybe integrating into level design). These will not function and I imagine can just be switched off in view, I just want to add them so we remember to factor them into any visual / design decisions.

**Comment by sinksinksink** [comment]
Excellent, it'll be good to have this in place. 

Note that I've added a variable for 'ammo' (see the commit log) to the player character that can maybe represent the charge level of the laser weapon, so maybe you can add this to the UI too.

**Comment by shauncg** [comment]
Ah okay. Yeah I will add that in too, no worries. I don't think there is going to be a charge level to the beam weapon; the game's design is intended to encourage you to KEEP FIRING, as it reduces your own heat level and increases your opponents. But I'll add it in because at least that way we have some variables to play with while we work out how to do the various bits.

**Comment by sinksinksink** [comment]
I think the mere fact it benefits you will keep you shooting, but I think there needs to be a limitation (maybe the ammo can represent the thermal capacity of the weapon as it's transferring heat from you to it, before it overloads - you stop shooting and it quickly returns to normal) so that there is more skill involved than simply nailing your finger to the LMB. 

Sorry for overlong sentence :)

**Comment by shauncg** [comment]
Yeah, sounds sensible. Am all up for prodding and probing the dreamt-up concept in the harsh light of reality!

**Comment by shauncg** [comment]
HUD in place and started to hook up variables. Need to speak with you to work out how to do the latter. I am stupid.

**Comment by shauncg** [comment]
HUD in place (moved to bottom so it doesn't clash with debug messages). Heat is now connected to BP_PlayerCharacter variable. Energy and Score aren't hooked up to anything. The latter can stay as text for now. Energy can be hooked up to Ammo when we need it. 

Only remaining task: ensure the progress bar updates in increments rather than going zero to hero. I think this just needs a max value declaring for the heat variable (call it 100 for now, that's probably easiest - or maybe 150 so that it doesn't look like a generic variable?)

**Comment by sinksinksink** [comment]
For the purposes of the milestone I'm closing this as it does what we need. Assigned back to you as you did this!
