### ISSUE TITLE
Shield sound FX

### ISSUE THREAD

**Issue by sinksinksink** [sinksinksink/FlyingDrunks#26]
There should be a sound played while the shield is active. Ideally this should be heard be all players.

**Comment by shauncg** [comment]
Added a shield sound effect. Tried to update the Blueprint to play audio when shield active = true, but couldn't get it to work. Based on my shitty understanding of the event graph, I think it's because there is no situation where that condition is being checked, but I don't know (1) how to make that happen without fucking up eventTick, or (2) if I'm even correct about why it's not working. 

Oh well, the fucking asset is there anyway.

**Comment by sinksinksink** [comment]
Did you leave any changes saved to the blueprint (can't see any)? Looks like we were both working on it at the same time and just want to check I've sorted it out properly!

**Comment by shauncg** [comment]
I think I did, yeah. They were floating beneath the other shield stuff IIRC. No worries if you wiped them, easy enough to reconstruct what didn't work!

**Comment by sinksinksink** [comment]
I found your version in the history (source control in the editor is actually great).

Couple of points:
- It's correct in that it checks whether the shield is active or not and plays a sound accordingly. 
- But it never triggers because it's not attached to an event (remember, flow is always white lines). The "get shield active node" is not an event, just a value of true or false.  

You could make it work in a few ways: 
- Add it to the end of the UseShield event as if that happens we are already using the shield and there will be no need to check if the ShieldActive variable is true.
- Connect up exactly what you did to the Tick event (put the branch node after the last current node). This might be better if we want a repeating sound as it will be called over and over and play a sound if the shield is active. 

Hope this helps!

**Comment by shauncg** [comment]
YAY WORKS NOW <3
